# Generated by Django 2.0 on 2017-12-26 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 12, 26, 10, 52, 47, 488017, tzinfo=utc))),
            ],
        ),
    ]
